### ISSUE TITLE
Backup fails

### ISSUE THREAD

**Issue by supar** [clandmeter/alpine-docker-gitlab#21]
Gitlab 17.6.2

```
docker compose exec gitlab entrypoint.sh backup

...
2024-12-26 13:44:47 UTC -- Dumping database ...
2024-12-26 13:44:47 UTC -- Dumping PostgreSQL database gitlab ...
2024-12-26 13:44:52 UTC -- [DONE]
2024-12-26 13:44:52 UTC -- Dumping database ... done
2024-12-26 13:44:52 UTC -- Dumping repositories ...
2024-12-26 13:44:52 UTC -- Deleting tar staging files ...
2024-12-26 13:44:52 UTC -- Cleaning up /home/git/gitlab/backups/db
2024-12-26 13:44:52 UTC -- Deleting tar staging files ... done
2024-12-26 13:44:52 UTC -- Deleting backups/tmp ...
2024-12-26 13:44:52 UTC -- Deleting backups/tmp ... done
2024-12-26 13:44:52 UTC -- Deleting backup and restore PID file at [/home/git/gitlab/tmp/backup_restore.pid]
rake aborted!
Backup::Error: gitaly-backup binary not found and gitaly_backup_path is not configured
/home/git/gitlab/lib/backup/gitaly_backup.rb:142:in `bin_path'
/home/git/gitlab/lib/backup/gitaly_backup.rb:31:in `start'
/home/git/gitlab/lib/backup/targets/repositories.rb:29:in `dump'
/home/git/gitlab/lib/backup/tasks/task.rb:25:in `backup!'
/home/git/gitlab/lib/backup/manager.rb:57:in `run_create_task'
/home/git/gitlab/lib/backup/manager.rb:145:in `block in run_all_create_tasks'
/home/git/gitlab/lib/backup/manager.rb:145:in `each_value'
/home/git/gitlab/lib/backup/manager.rb:145:in `run_all_create_tasks'
/home/git/gitlab/lib/backup/manager.rb:32:in `create!'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:12:in `block in create_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:75:in `lock_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:10:in `create_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:117:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli.rb:455:in `exec'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli.rb:29:in `start'
/usr/local/bundle/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => gitlab:backup:create
(See full trace by running task with --trace)
```

**Comment by supar** [comment]
Possible fix of the Dockerfile

```
+FROM alpinelinux/docker-gitlab/gitaly:${GITALY_SERVER_VERSION} as gitaly

+COPY --from=gitaly /usr/local/bin/gitaly-backup /usr/local/bin/gitaly-backup
```

**Comment by Ikke** [comment]
@supar I've implemented your suggestion, but I did not verify if it's possible to make a backup yet. Can you try (should be available in the 17.7-stable branch)
